name: floor_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 1.4.2
homepage: https://pinchbv.github.io/floor/
repository: https://github.com/pinchbv/floor
issue_tracker: https://github.com/pinchbv/floor/issues
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.2
  build_config: ^1.1.2
  code_builder: ^4.10.1
  collection: ^1.19.1
  floor_annotation:
    path: ../floor_annotation
  meta:
  source_gen: ^2.0.0
  strings: ^3.2.0

dev_dependencies:
  build_test: ^2.2.3
  dart_style: ^3.0.1
  mockito: ^5.4.5
  path: ^1.9.1
  pub_semver: ^2.1.5
  test: ^1.25.15
